Update dependabot-merger.yml

diff --git a/.github/workflows/dependabot-merger.yml b/.github/workflows/dependabot-merger.yml
--- a/.github/workflows/dependabot-merger.yml
+++ b/.github/workflows/dependabot-merger.yml
@@ -16,24 +16,29 @@ jobs:
 
       - name: Ensure test branch is up to date with master
         run: |
-          git config --global user.email "github-action-bot@example.com"
-          git config --global user.name "GitHub Action Bot"
+          git config --global user.email "dependabot-merger-bot@branch.io"
+          git config --global user.name "Dependabot Merger Bot"
           git checkout master
           git pull
           git checkout dependabot-test-branch
-          git merge master --allow-unrelated-histories
+          git merge master --allow-unrelated-histories || echo "Failed to merge master into test branch."
 
       - name: Get list of PRs from dependabot
         id: pr_list
         run: |
-          echo "::set-output name=numbers::$(gh pr list | grep dependabot | awk '{print $1}')"
-
+          PR_LIST=$(gh pr list | grep dependabot | awk '{print $1}')
+          echo "::set-output name=numbers::$PR_LIST"
+          echo "PRs to be merged: $PR_LIST"
+          
       - name: Merge PRs into test branch
         run: |
           IFS=' ' read -r -a array <<< "${{ steps.pr_list.outputs.numbers }}"
+          git checkout dependabot-test-branch
           for PR_NUMBER in "${array[@]}"
           do
-            gh pr checkout $PR_NUMBER
-            git merge --no-ff -m "Merging PR #$PR_NUMBER via GitHub Action"
+            echo "Merging PR #$PR_NUMBER into test branch..."
+            git fetch origin pull/$PR_NUMBER/head:pr$PR_NUMBER
+            git merge --no-ff pr$PR_NUMBER -m "Merging Dependabot PR #$PR_NUMBER via GitHub Action"
+            echo "Pushing changes to dependabot-test-branch..."
             git push origin dependabot-test-branch
           done
